import { CHAT_MODELS } from '@/constants/chat';
import { FISH_DEFAULT_TTS_MODEL, FLUX_DEFAULT_MODEL, GROKVIDEO_DEFAULT_MODEL, HAILUO_DEFAULT_MODEL, KLING_DEFAULT_MODEL, NANOBANANA_DEFAULT_MODEL, OMNI_DEFAULT_MODEL, OPENAIIMAGE_DEFAULT_MODEL, PIXVERSE_DEFAULT_MODEL, PRODUCER_DEFAULT_MODEL, SEEDANCE_DEFAULT_MODEL, SEEDREAM_DEFAULT_MODEL, SORA_DEFAULT_MODEL, SUNO_DEFAULT_MODEL, VEO_DEFAULT_MODEL, WAN_DEFAULT_MODEL } from '@/constants';
import type { IChatModel } from '@/models/chat';
import { getLegacyCapabilityMapping } from './mappings';
import type { ModelCapability,ModelCategory,ModelRegistryItem } from './types';
export interface LegacyModelDescriptor { id:string; capability:string; name?:string; description?:string; enabled?:boolean; isDefault?:boolean; sortOrder?:number; capabilities?:readonly ModelCapability[]; category?:ModelCategory; provider?:string; source:string; config?:unknown; }
export type LegacyModelSource=()=>readonly LegacyModelDescriptor[];
const chatCapabilities=(m:IChatModel):ModelCapability[]=>['chat','text-generation',...(m.isReasoningSupported?['reasoning' as const]:[]),...(m.isSearchSupported?['web-search' as const]:[]),...(m.isDeepSearchSupported?['deep-search' as const]:[]),...(m.isImageSupported?['image-input' as const]:[]),...(m.isFileSupported?['file-input' as const]:[])];
export const legacyChatModelSource:LegacyModelSource=()=>CHAT_MODELS.map((m,index)=>({id:m.name,capability:m.modelGroup??'chatgpt',name:m.getDisplayName(),description:m.getDescription(),enabled:m.enabled!==false,sortOrder:index,capabilities:chatCapabilities(m),source:'constants/chat.CHAT_MODELS',config:m}));
/** Models exposed by legacy constants without importing stores or Vue components. */
export const LEGACY_CONFIG_MODELS:readonly LegacyModelDescriptor[]=[
{id:FLUX_DEFAULT_MODEL,capability:'flux',isDefault:true,source:'constants/flux.FLUX_DEFAULT_MODEL'},{id:NANOBANANA_DEFAULT_MODEL,capability:'nanobanana',isDefault:true,source:'constants/nanobanana.NANOBANANA_DEFAULT_MODEL'},{id:OPENAIIMAGE_DEFAULT_MODEL,capability:'openaiimage',isDefault:true,source:'constants/openaiimage.OPENAIIMAGE_DEFAULT_MODEL'},{id:SEEDREAM_DEFAULT_MODEL,capability:'seedream',isDefault:true,source:'constants/seedream.SEEDREAM_DEFAULT_MODEL'},
{id:KLING_DEFAULT_MODEL,capability:'kling',isDefault:true,source:'constants/kling.KLING_DEFAULT_MODEL'},{id:VEO_DEFAULT_MODEL,capability:'veo',isDefault:true,source:'constants/veo.VEO_DEFAULT_MODEL'},{id:SORA_DEFAULT_MODEL,capability:'sora',isDefault:true,source:'constants/sora.SORA_DEFAULT_MODEL'},{id:PIXVERSE_DEFAULT_MODEL,capability:'pixverse',isDefault:true,source:'constants/pixverse.PIXVERSE_DEFAULT_MODEL'},{id:HAILUO_DEFAULT_MODEL,capability:'hailuo',isDefault:true,source:'constants/hailuo.HAILUO_DEFAULT_MODEL'},{id:SEEDANCE_DEFAULT_MODEL,capability:'seedance',isDefault:true,source:'constants/seedance.SEEDANCE_DEFAULT_MODEL'},{id:GROKVIDEO_DEFAULT_MODEL,capability:'grokvideo',isDefault:true,source:'constants/grokvideo.GROKVIDEO_DEFAULT_MODEL'},{id:OMNI_DEFAULT_MODEL,capability:'omni',isDefault:true,source:'constants/omni.OMNI_DEFAULT_MODEL'},{id:WAN_DEFAULT_MODEL,capability:'wan',isDefault:true,source:'constants/wan.WAN_DEFAULT_MODEL'},
{id:SUNO_DEFAULT_MODEL,capability:'suno',isDefault:true,source:'constants/suno.SUNO_DEFAULT_MODEL'},{id:PRODUCER_DEFAULT_MODEL,capability:'producer',isDefault:true,source:'constants/producer.PRODUCER_DEFAULT_MODEL'},{id:FISH_DEFAULT_TTS_MODEL,capability:'fish',isDefault:true,source:'constants/fish.FISH_DEFAULT_TTS_MODEL'}];
export const legacyConfigModelSource:LegacyModelSource=()=>LEGACY_CONFIG_MODELS;
export function adaptLegacyModels(sources:readonly LegacyModelSource[]):ModelRegistryItem[]{let order=0;const seen=new Set<string>();return sources.flatMap(source=>source()).map(item=>{const mapping=getLegacyCapabilityMapping(item.capability);if(!mapping&&!item.provider)throw new Error(`Unknown legacy capability: ${item.capability}`);const provider=item.provider??mapping!.provider;const registryId=`${provider}:${item.id}`;if(seen.has(registryId))throw new Error(`Duplicate model registry id: ${registryId}`);seen.add(registryId);return Object.freeze({id:registryId,legacyId:item.id,name:item.name??item.id,description:item.description,provider,category:item.category??mapping!.category,capabilities:Object.freeze([...(item.capabilities??mapping!.capabilities)]),enabled:item.enabled!==false,isDefault:item.isDefault===true,sortOrder:item.sortOrder??order++,source:'legacy' as const,legacySource:item.source,legacyConfig:item.config});});}
