import type { ModelCapability,ModelCategory,ModelProvider } from './types';
export interface LegacyCapabilityMapping { provider:ModelProvider; category:ModelCategory; capabilities:readonly ModelCapability[]; }
export const LEGACY_CAPABILITY_MAPPING:Readonly<Record<string,LegacyCapabilityMapping>>=Object.freeze({
chatgpt:{provider:'openai',category:'chat',capabilities:['chat','text-generation']},claude:{provider:'anthropic',category:'chat',capabilities:['chat','text-generation']},gemini:{provider:'google',category:'chat',capabilities:['chat','text-generation']},grok:{provider:'xai',category:'chat',capabilities:['chat','text-generation']},deepseek:{provider:'deepseek',category:'chat',capabilities:['chat','text-generation']},kimi:{provider:'moonshot',category:'chat',capabilities:['chat','text-generation']},glm:{provider:'zhipu',category:'chat',capabilities:['chat','text-generation']},
midjourney:{provider:'midjourney',category:'images',capabilities:['image-generation']},flux:{provider:'black-forest-labs',category:'images',capabilities:['image-generation','image-editing']},nanobanana:{provider:'google',category:'images',capabilities:['image-generation','image-editing']},openaiimage:{provider:'openai',category:'images',capabilities:['image-generation','image-editing']},seedream:{provider:'bytedance',category:'images',capabilities:['image-generation','image-editing']},
luma:{provider:'luma',category:'video',capabilities:['video-generation']},pika:{provider:'pika',category:'video',capabilities:['video-generation']},kling:{provider:'kuaishou',category:'video',capabilities:['video-generation']},veo:{provider:'google',category:'video',capabilities:['video-generation']},sora:{provider:'openai',category:'video',capabilities:['video-generation']},pixverse:{provider:'pixverse',category:'video',capabilities:['video-generation']},hailuo:{provider:'minimax',category:'video',capabilities:['video-generation']},seedance:{provider:'bytedance',category:'video',capabilities:['video-generation']},grokvideo:{provider:'xai',category:'video',capabilities:['video-generation']},omni:{provider:'acedatacloud',category:'video',capabilities:['video-generation']},wan:{provider:'alibaba',category:'video',capabilities:['video-generation']},
suno:{provider:'suno',category:'music',capabilities:['music-generation']},producer:{provider:'acedatacloud',category:'music',capabilities:['music-generation']},fish:{provider:'fish-audio',category:'voice',capabilities:['speech-generation']}});
export const getLegacyCapabilityMapping=(key:string)=>LEGACY_CAPABILITY_MAPPING[key];
export const getProviderForLegacyCapability=(key:string)=>getLegacyCapabilityMapping(key)?.provider;
export const getCategoryForLegacyCapability=(key:string)=>getLegacyCapabilityMapping(key)?.category;
