import { describe, expect, it } from 'vitest';
import { normalizeAccount, normalizeAccountSummary, normalizeLedger, validateAccountIdentifier, validateAccountStatus, validateConsumptionAmount, validateLedgerReference, validateLedgerType, validateReservationAmount, validateTokenAmount } from '../commercial-domain';
const account = { identifier: 'account-1', status: 'active' as const, profile: { displayName: 'Workspace', locale: 'en-US', country: 'US', timeZone: 'UTC', ignored: 'x' }, limits: { tokenLimit: '1000', reservationLimit: '100', ignored: 'x' } };
const ledgerSummary = { openingBalance: '10', credits: '20', consumptions: '5', reservations: '2', releases: '1', adjustments: '0', closingBalance: '24', entryCount: '4' };
const capabilities = { accountAvailable: true, billingAvailable: false, paymentsAvailable: false, subscriptionsAvailable: false, walletAvailable: true, purchaseHistoryAvailable: false, ordersAvailable: false, transactionsAvailable: false, invoicesAvailable: false, tokenReservationsAvailable: true, tokenLedgerAvailable: true };
describe('Commercial account domain', () => {
  it('freezes allowlisted account without mutation', () => { const before = JSON.stringify(account); const value = normalizeAccount(account); expect(JSON.stringify(account)).toBe(before); expect(JSON.stringify(value)).not.toContain('ignored'); expect(Object.isFrozen(value.profile)).toBe(true); expect(Object.isFrozen(value.limits)).toBe(true); });
  it('validates integer minor token amounts deterministically', () => { for (const validate of [validateTokenAmount, validateReservationAmount, validateConsumptionAmount]) { expect(validate('42')).toEqual({ valid: true, value: '42' }); expect(validate('1.5')).toEqual({ valid: false, code: 'invalid-value' }); expect(validate('-1')).toEqual({ valid: false, code: 'invalid-value' }); } });
  it('validates closed references, status and ledger type', () => { expect(validateAccountIdentifier('account-1').valid).toBe(true); expect(validateLedgerReference('ledger:1').valid).toBe(true); expect(validateAccountStatus('active').valid).toBe(true); expect(validateAccountStatus('x').valid).toBe(false); expect(validateLedgerType('reservation').valid).toBe(true); expect(validateLedgerType('payment').valid).toBe(false); });
  it('deeply freezes safe ledger fields', () => { const value = normalizeLedger({ entries: [{ reference: 'entry-1', type: 'credit', amount: '20', occurredAt: '2026-01-01T00:00:00Z', businessReference: 'order-1' }], summary: ledgerSummary }); expect(Object.isFrozen(value.entries)).toBe(true); expect(Object.isFrozen(value.entries[0])).toBe(true); expect(Object.isFrozen(value.summary)).toBe(true); });
  it('deeply freezes account summary', () => { const value = normalizeAccountSummary({ account, tokenBalance: { available: '24', reserved: '2' }, ledgerSummary, capabilities }); expect(value.tokenBalance).toEqual({ available: '24', reserved: '2', unit: 'token' }); expect(Object.isFrozen(value.account.profile)).toBe(true); expect(Object.isFrozen(value.capabilities)).toBe(true); });
});
