import { describe, expect, it } from 'vitest';
import { calculateUsageCost, normalizeCostBreakdown, normalizePricing, normalizePricingSnapshot, normalizeQuota, normalizeUsage, validateBillableAmount, validateCurrencyCode, validatePricingIdentifier, validatePricingStatus, validatePricingUnit, validateQuotaAmount, validateUsageQuantity } from '../commercial-domain';
const pricing = { identifier: 'price-1', status: 'active' as const, currency: 'USD', unit: 'token' as const, tiers: [{ minimumQuantity: '0', maximumQuantity: null, unitPriceMinor: '2', unknown: 'excluded' }] };
const quotaSummary = { quota: { identifier: 'quota-1', limit: '1000', unit: 'token' as const, period: 'monthly' as const }, usage: { consumed: '100', reserved: '20', remaining: '880' }, allowances: [{ identifier: 'allowance-1', amount: '50', unit: 'token' as const }] };
const snapshot = { pricing, usageSummary: { totalQuantity: '100', billableQuantity: '80', unit: 'token' as const, recordCount: '2' }, costSummary: { subtotal: { amountMinor: '160', currency: 'USD' }, adjustments: { amountMinor: '0', currency: 'USD' }, total: { amountMinor: '160', currency: 'USD' } }, quotaSummary };
describe('Commercial pricing, usage cost and quota domain', () => {
  it('normalizes deeply immutable allowlisted pricing without mutation', () => { const before = JSON.stringify(pricing); const value = normalizePricing(pricing); expect(JSON.stringify(pricing)).toBe(before); expect(JSON.stringify(value)).not.toContain('unknown'); expect(Object.isFrozen(value.tiers)).toBe(true); expect(Object.isFrozen(value.tiers[0])).toBe(true); });
  it('validates canonical integer strings only', () => { for (const validate of [validateUsageQuantity, validateBillableAmount, validateQuotaAmount]) { expect(validate('0')).toEqual({ valid: true, value: '0' }); expect(validate('1000')).toEqual({ valid: true, value: '1000' }); for (const rejected of ['1.5', '0.1', '1e3', '-1', '01']) expect(validate(rejected).valid).toBe(false); } });
  it('validates identifiers, status, unit and currency', () => { expect(validatePricingIdentifier('price-1').valid).toBe(true); expect(validatePricingStatus('active').valid).toBe(true); expect(validatePricingUnit('token').valid).toBe(true); expect(validateCurrencyCode('USD').valid).toBe(true); expect(validatePricingUnit('provider-unit').valid).toBe(false); });
  it('calculates costs using integer arithmetic', () => { expect(calculateUsageCost('80', '2', 'USD')).toEqual({ valid: true, value: { amountMinor: '160', currency: 'USD' } }); expect(calculateUsageCost('1.5', '2', 'USD')).toEqual({ valid: false, code: 'invalid-quantity' }); });
  it('normalizes usage, cost and quota as frozen values', () => { const usage = normalizeUsage([{ reference: 'usage-1', quantity: { value: '80', unit: 'token' }, occurredAt: '2026-01-01T00:00:00Z' }]); const breakdown = normalizeCostBreakdown({ pricingIdentifier: 'price-1', quantity: '80', unitPriceMinor: '2', cost: { amountMinor: '160', currency: 'USD' } }); const quota = normalizeQuota(quotaSummary); expect(Object.isFrozen(usage[0]?.quantity)).toBe(true); expect(Object.isFrozen(breakdown.cost)).toBe(true); expect(Object.isFrozen(quota.allowances[0])).toBe(true); });
  it('creates a deeply frozen pricing snapshot', () => { const value = normalizePricingSnapshot(snapshot); expect(Object.isFrozen(value)).toBe(true); expect(Object.isFrozen(value.pricing.tiers[0])).toBe(true); expect(Object.isFrozen(value.costSummary.total)).toBe(true); expect(Object.isFrozen(value.quotaSummary.usage)).toBe(true); });
});
