import { describe, expect, expectTypeOf, it } from 'vitest';
import { createWorkspaceCommercialCapabilities, normalizeInvoice, normalizeOrder, normalizeTokenBalance, validateCountryCode, validateCurrencyCode, validateInvoiceId, validateIsoDateTime, validateLanguageCode, validateLocaleCode, validateMonetaryValue, validateOrderId, validateReferenceId, validateTimeZoneIdentifier, validateTokenBalance, validateTransactionId } from '../commercial-domain';
import type { BillingAccountSource, InvoiceSource, OrderHistorySource, PaymentAvailabilitySource, PurchaseHistorySource, SubscriptionSource, TokenBalanceSource, TransactionHistorySource, WalletSource, WorkspaceCommercialCapabilities, WorkspaceInternationalCommercialContract, WorkspacePaymentCategory, WorkspaceProfileSource, WorkspaceTaxationModel, WorkspaceInvoiceFormat } from '../commercial-domain';
describe('Workspace commercial domain boundary', () => {
  it('defines read-only source contracts', () => { expectTypeOf<TokenBalanceSource['readTokenBalance']>().toBeFunction(); expectTypeOf<BillingAccountSource['readBillingAccount']>().toBeFunction(); expectTypeOf<WorkspaceProfileSource['readWorkspaceProfile']>().toBeFunction(); expectTypeOf<PurchaseHistorySource['readPurchaseHistory']>().toBeFunction(); expectTypeOf<OrderHistorySource['readOrders']>().toBeFunction(); expectTypeOf<TransactionHistorySource['readTransactions']>().toBeFunction(); expectTypeOf<InvoiceSource['readInvoices']>().toBeFunction(); expectTypeOf<SubscriptionSource['readSubscription']>().toBeFunction(); expectTypeOf<WalletSource['readWallet']>().toBeFunction(); expectTypeOf<PaymentAvailabilitySource['readPaymentAvailability']>().toBeFunction(); });
  it('validates primitives without exposing rejected input', () => { expect(validateMonetaryValue('1200')).toEqual({ valid: true, value: '1200' }); expect(validateTokenBalance('-1')).toEqual({ valid: false, code: 'invalid-value' }); expect(validateCurrencyCode('USD').valid).toBe(true); expect(validateLocaleCode('en-US').valid).toBe(true); expect(validateLanguageCode('en').valid).toBe(true); expect(validateCountryCode('US').valid).toBe(true); expect(validateTimeZoneIdentifier('Europe/Paris').valid).toBe(true); expect(validateIsoDateTime('2026-01-02T03:04:05Z').valid).toBe(true); expect(validateReferenceId('acct_123').valid).toBe(true); expect(validateInvoiceId('inv-1').valid).toBe(true); expect(validateOrderId('ord-1').valid).toBe(true); expect(validateTransactionId('txn-1').valid).toBe(true); expect(validateCurrencyCode('usd')).toEqual({ valid: false, code: 'invalid-format' }); });
  it('normalizes without mutation', () => { const input = Object.freeze({ reference: 'ord-1', total: Object.freeze({ amountMinor: '500', currency: 'EUR' }), status: 'completed' as const }); const before = JSON.stringify(input); const order = normalizeOrder(input); expect(JSON.stringify(input)).toBe(before); expect(order).toEqual(input); expect(Object.isFrozen(order)).toBe(true); expect(Object.isFrozen(order.total)).toBe(true); expect(normalizeTokenBalance({ available: '10', reserved: '2' })).toEqual({ available: '10', reserved: '2', unit: 'token' }); expect(Object.isFrozen(normalizeInvoice({ reference: 'inv-1', total: { amountMinor: '500', currency: 'EUR' }, status: 'paid', issuedAt: '2026-01-02T03:04:05Z' }))).toBe(true); });
  it('creates immutable capability projections', () => { const input: WorkspaceCommercialCapabilities = { accountAvailable: true, billingAvailable: true, paymentsAvailable: false, subscriptionsAvailable: false, walletAvailable: true, purchaseHistoryAvailable: true, ordersAvailable: true, transactionsAvailable: true, invoicesAvailable: false }; const projection = createWorkspaceCommercialCapabilities(input); expect(projection).toEqual(input); expect(projection).not.toBe(input); expect(Object.isFrozen(projection)).toBe(true); });
  it('supports neutral international and payment categories', () => { expectTypeOf<WorkspacePaymentCategory>().toEqualTypeOf<'bank-card' | 'digital-wallet' | 'crypto-payment' | 'local-payment-method' | 'internal-balance'>(); expectTypeOf<WorkspaceInternationalCommercialContract['taxationModels']>().toEqualTypeOf<readonly WorkspaceTaxationModel[]>(); expectTypeOf<WorkspaceInternationalCommercialContract['invoiceFormats']>().toEqualTypeOf<readonly WorkspaceInvoiceFormat[]>(); });
});
