import { describe, expect, it } from 'vitest';
import { assembleCommercialSnapshot, createCommercialSnapshot, createEmptySnapshot, createSnapshotResult } from '../commercial-domain';
import type { WorkspaceCommercialSourceRegistry } from '../commercial-domain';
const profile = Object.freeze({ reference: 'profile-1', locale: 'en-US', country: 'US', timeZone: 'UTC' }); const balance = Object.freeze({ available: '10', reserved: '2', unit: 'token' as const });
const completeRegistry = (): WorkspaceCommercialSourceRegistry => Object.freeze({ profile: { readWorkspaceProfile: async () => profile }, tokenBalance: { readTokenBalance: async () => balance }, billingAccount: { readBillingAccount: async () => ({ accountReference: 'billing-1', status: 'active' as const }) }, purchaseHistory: { readPurchaseHistory: async () => ({ orders: [], transactions: [] }) }, orders: { readOrders: async () => [{ reference: 'order-1', total: { amountMinor: '100', currency: 'USD' }, status: 'completed' as const }] }, transactions: { readTransactions: async () => [] }, invoices: { readInvoices: async () => [] }, subscription: { readSubscription: async () => ({ reference: 'subscription-1', status: 'active' as const, renewsAt: null }) }, wallet: { readWallet: async () => ({ reference: 'wallet-1', tokenBalance: balance }) }, paymentAvailability: { readPaymentAvailability: async () => [{ country: 'US', currency: 'USD', available: true }] } });
describe('Unified commercial read snapshot', () => {
  it('reports deterministic unavailability', async () => { const result = await createCommercialSnapshot({}); expect(result.state).toBe('unavailable'); expect(result.issues).toHaveLength(10); expect(Object.isFrozen(result.issues)).toBe(true); });
  it('assembles complete sources', async () => { const result = await createCommercialSnapshot(completeRegistry()); expect(result.state).toBe('ready'); expect(result.issues).toEqual([]); expect(result.snapshot.capabilities.paymentsAvailable).toBe(true); });
  it('sanitizes failures', async () => { const result = await createCommercialSnapshot({ profile: { readWorkspaceProfile: async () => profile }, tokenBalance: { readTokenBalance: async () => { throw new Error('private provider failure'); } } }); expect(result.state).toBe('partial'); expect(result.issues).toContainEqual({ domain: 'token-balance', code: 'source-failed' }); expect(JSON.stringify(result)).not.toContain('private provider failure'); });
  it('rejects invalid runtime values', async () => { const registry = { orders: { readOrders: async () => ({ unsafe: true }) } } as unknown as WorkspaceCommercialSourceRegistry; const result = await createCommercialSnapshot(registry); expect(result.issues).toContainEqual({ domain: 'orders', code: 'invalid-data' }); expect(JSON.stringify(result)).not.toContain('unsafe'); });
  it('allowlists and deeply freezes without mutation', () => { const input = { profile: { ...profile, secret: 'excluded' }, tokenBalance: balance, billingAccount: null, purchases: null, orders: [{ reference: 'order-1', total: { amountMinor: '5', currency: 'EUR' }, status: 'completed' as const }], transactions: [], invoices: [], subscription: null, wallet: null, paymentAvailability: [] }; const before = JSON.stringify(input); const snapshot = assembleCommercialSnapshot(input); expect(JSON.stringify(input)).toBe(before); expect(JSON.stringify(snapshot)).not.toContain('secret'); expect(Object.isFrozen(snapshot.orders[0]?.total)).toBe(true); expect(Object.isFrozen(snapshot.capabilities)).toBe(true); });
  it('creates an immutable empty result', () => { const result = createSnapshotResult(createEmptySnapshot(), [{ domain: 'profile', code: 'source-unavailable' }]); expect(result.state).toBe('unavailable'); expect(Object.isFrozen(result.issues[0])).toBe(true); });
});
