import { beforeEach, describe, expect, it, vi } from 'vitest';
const state = vi.hoisted(() => ({ enabled: false, load: vi.fn<() => Promise<object | null>>() }));
vi.mock('@/utils/featureFlag', () => ({ isFeatureEnabled: vi.fn(() => state.enabled) }));
vi.mock('@/workspace', () => ({ UNIFIED_AI_WORKSPACE_FEATURE_FLAG: 'unified-ai-workspace', createWorkspaceEntry: () => ({ featureFlag: 'unified-ai-workspace', isEnabled: () => state.enabled, load: state.load }) }));
describe('Workspace integration bridge', () => {
  beforeEach(() => { vi.resetModules(); state.enabled = false; state.load.mockReset(); });
  it('tracks initialization and disabled runtime without activation', async () => { const integration = await import('../index'); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'idle', lifecycle: 'workspace-initialization' }); expect(integration.getWorkspaceNavigationEntry()).toBeNull(); expect(await integration.loadWorkspaceFoundation()).toBeNull(); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'disabled', lifecycle: 'feature-disabled' }); expect(state.load).not.toHaveBeenCalled(); });
  it('tracks enabled lifecycle and memoizes Foundation loading', async () => { const integration = await import('../index'); let resolveFoundation: ((value: object) => void) | undefined; const pending = new Promise<object>((resolve) => { resolveFoundation = resolve; }); state.enabled = true; state.load.mockReturnValue(pending); const first = integration.loadWorkspaceFoundation(); const second = integration.loadWorkspaceFoundation(); expect(first).toBe(second); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'loading', lifecycle: 'foundation-loading' }); resolveFoundation?.(Object.freeze({ shell: Object.freeze({}) })); await expect(first).resolves.toBeTruthy(); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'ready', lifecycle: 'foundation-ready' }); expect(state.load).toHaveBeenCalledTimes(1); });
  it('contains rejected imports using sanitized diagnostics', async () => { const integration = await import('../index'); state.enabled = true; state.load.mockRejectedValue(new Error('sensitive internal failure')); const first = integration.loadWorkspaceFoundation(); expect(integration.loadWorkspaceFoundation()).toBe(first); await expect(first).resolves.toBeNull(); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'unavailable', lifecycle: 'foundation-unavailable' }); expect(JSON.stringify(integration.getWorkspaceRuntimeSnapshot())).not.toContain('sensitive'); expect(state.load).toHaveBeenCalledTimes(1); });
  it('treats an empty Foundation result as unavailable', async () => { const integration = await import('../index'); state.enabled = true; state.load.mockResolvedValue(null); await expect(integration.loadWorkspaceFoundation()).resolves.toBeNull(); expect(integration.getWorkspaceRuntimeSnapshot()).toEqual({ status: 'unavailable', lifecycle: 'foundation-unavailable' }); });
});
