import WorkspaceShell from './components/WorkspaceShell.vue';
import WorkspaceHeader from './components/WorkspaceHeader.vue';
import WorkspaceLeftSidebar from './components/WorkspaceLeftSidebar.vue';
import WorkspaceMainArea from './components/WorkspaceMainArea.vue';
import WorkspaceRightSidebar from './components/WorkspaceRightSidebar.vue';
import WorkspaceRouterView from './components/WorkspaceRouterView.vue';
import WorkspaceNotificationLayer from './components/layers/WorkspaceNotificationLayer.vue';
import WorkspaceModalLayer from './components/layers/WorkspaceModalLayer.vue';
import WorkspaceOverlayLayer from './components/layers/WorkspaceOverlayLayer.vue';
import WorkspaceComposerHost from './components/hosts/WorkspaceComposerHost.vue';
import WorkspaceModelSwitcherHost from './components/hosts/WorkspaceModelSwitcherHost.vue';
import WorkspaceContextHost from './components/hosts/WorkspaceContextHost.vue';
import WorkspaceToolHost from './components/hosts/WorkspaceToolHost.vue';
import TextWorkspaceSlot from './components/slots/TextWorkspaceSlot.vue';
import ImageWorkspaceSlot from './components/slots/ImageWorkspaceSlot.vue';
import VideoWorkspaceSlot from './components/slots/VideoWorkspaceSlot.vue';
import AudioWorkspaceSlot from './components/slots/AudioWorkspaceSlot.vue';
import ToolsWorkspaceSlot from './components/slots/ToolsWorkspaceSlot.vue';
import type { WorkspaceFoundation } from './types';
export const workspaceFoundation: WorkspaceFoundation = Object.freeze({ shell: WorkspaceShell, header: WorkspaceHeader, leftSidebar: WorkspaceLeftSidebar, mainArea: WorkspaceMainArea, rightSidebar: WorkspaceRightSidebar, routerView: WorkspaceRouterView, notificationLayer: WorkspaceNotificationLayer, modalLayer: WorkspaceModalLayer, overlayLayer: WorkspaceOverlayLayer, hosts: Object.freeze({ composer: WorkspaceComposerHost, modelSwitcher: WorkspaceModelSwitcherHost, context: WorkspaceContextHost, tool: WorkspaceToolHost }), slots: Object.freeze({ text: TextWorkspaceSlot, image: ImageWorkspaceSlot, video: VideoWorkspaceSlot, audio: AudioWorkspaceSlot, tools: ToolsWorkspaceSlot }) });
