import type { WorkspaceAccountCapabilities, WorkspaceAccountContract, WorkspaceAccountSummary, WorkspaceTokenLedger, WorkspaceTokenLedgerEntry, WorkspaceTokenLedgerSummary } from './account';
import { createWorkspaceCommercialCapabilities } from './projection';
import { normalizeTokenBalance } from './normalization';
export interface WorkspaceAccountReadModel { readonly identifier: string; readonly status: WorkspaceAccountContract['status']; readonly profile: WorkspaceAccountContract['profile']; readonly limits: WorkspaceAccountContract['limits']; }
export interface WorkspaceTokenLedgerReadModel { readonly entries: readonly WorkspaceTokenLedgerEntry[]; readonly summary: WorkspaceTokenLedgerSummary; }
export interface WorkspaceAccountSummaryReadModel { readonly account: WorkspaceAccountReadModel; readonly tokenBalance: { readonly available: string; readonly reserved: string }; readonly ledgerSummary: WorkspaceTokenLedgerSummary; readonly capabilities: WorkspaceAccountCapabilities; }
const normalizeCapabilities = (value: WorkspaceAccountCapabilities): WorkspaceAccountCapabilities => Object.freeze({ ...createWorkspaceCommercialCapabilities(value), tokenReservationsAvailable: value.tokenReservationsAvailable, tokenLedgerAvailable: value.tokenLedgerAvailable });
const normalizeLedgerSummary = (value: WorkspaceTokenLedgerSummary): WorkspaceTokenLedgerSummary => Object.freeze({ openingBalance: value.openingBalance, credits: value.credits, consumptions: value.consumptions, reservations: value.reservations, releases: value.releases, adjustments: value.adjustments, closingBalance: value.closingBalance, entryCount: value.entryCount });
export const normalizeAccount = (value: WorkspaceAccountReadModel): WorkspaceAccountContract => Object.freeze({ identifier: value.identifier, status: value.status, profile: Object.freeze({ displayName: value.profile.displayName, locale: value.profile.locale, country: value.profile.country, timeZone: value.profile.timeZone }), limits: Object.freeze({ tokenLimit: value.limits.tokenLimit, reservationLimit: value.limits.reservationLimit }) });
export const normalizeLedger = (value: WorkspaceTokenLedgerReadModel): WorkspaceTokenLedger => Object.freeze({ entries: Object.freeze(value.entries.map(entry => Object.freeze({ reference: entry.reference, type: entry.type, amount: entry.amount, occurredAt: entry.occurredAt, businessReference: entry.businessReference }))), summary: normalizeLedgerSummary(value.summary) });
export const normalizeAccountSummary = (value: WorkspaceAccountSummaryReadModel): WorkspaceAccountSummary => Object.freeze({ account: normalizeAccount(value.account), tokenBalance: normalizeTokenBalance(value.tokenBalance), ledgerSummary: normalizeLedgerSummary(value.ledgerSummary), capabilities: normalizeCapabilities(value.capabilities) });
