import type { BillingAccountSource, InvoiceSource, OrderHistorySource, PaymentAvailabilitySource, PurchaseHistorySource, SubscriptionSource, TokenBalanceSource, TransactionHistorySource, WalletSource, WorkspaceProfileSource } from './contracts';
import type { WorkspaceCommercialDomain, WorkspaceCommercialIssue, WorkspaceCommercialSnapshotInput, WorkspaceCommercialSnapshotResult } from './snapshot';
import { assembleCommercialSnapshot, createSnapshotResult } from './snapshot';
export interface WorkspaceCommercialSourceRegistry { readonly tokenBalance?: TokenBalanceSource; readonly billingAccount?: BillingAccountSource; readonly profile?: WorkspaceProfileSource; readonly purchaseHistory?: PurchaseHistorySource; readonly orders?: OrderHistorySource; readonly transactions?: TransactionHistorySource; readonly invoices?: InvoiceSource; readonly subscription?: SubscriptionSource; readonly wallet?: WalletSource; readonly paymentAvailability?: PaymentAvailabilitySource; }
type ReadOutcome<T> = Readonly<{ readonly value: T | null; readonly issue: WorkspaceCommercialIssue | null }>;
const readSource = async <T>(domain: WorkspaceCommercialDomain, read: (() => Promise<T | null>) | undefined, validate: (value: T) => boolean): Promise<ReadOutcome<T>> => { if (!read) return Object.freeze({ value: null, issue: Object.freeze({ domain, code: 'source-unavailable' }) }); try { const value = await read(); if (value === null) return Object.freeze({ value: null, issue: Object.freeze({ domain, code: 'source-unavailable' }) }); return validate(value) ? Object.freeze({ value, issue: null }) : Object.freeze({ value: null, issue: Object.freeze({ domain, code: 'invalid-data' }) }); } catch { return Object.freeze({ value: null, issue: Object.freeze({ domain, code: 'source-failed' }) }); } };
const objectValue = (value: unknown): boolean => typeof value === 'object' && value !== null && !Array.isArray(value);
const arrayValue = (value: unknown): boolean => Array.isArray(value);
export const createCommercialSnapshot = async (registry: WorkspaceCommercialSourceRegistry): Promise<WorkspaceCommercialSnapshotResult> => {
  const reads = await Promise.all([readSource('profile', registry.profile?.readWorkspaceProfile.bind(registry.profile), objectValue), readSource('token-balance', registry.tokenBalance?.readTokenBalance.bind(registry.tokenBalance), objectValue), readSource('billing-account', registry.billingAccount?.readBillingAccount.bind(registry.billingAccount), objectValue), readSource('purchase-history', registry.purchaseHistory?.readPurchaseHistory.bind(registry.purchaseHistory), objectValue), readSource('orders', registry.orders?.readOrders.bind(registry.orders), arrayValue), readSource('transactions', registry.transactions?.readTransactions.bind(registry.transactions), arrayValue), readSource('invoices', registry.invoices?.readInvoices.bind(registry.invoices), arrayValue), readSource('subscription', registry.subscription?.readSubscription.bind(registry.subscription), objectValue), readSource('wallet', registry.wallet?.readWallet.bind(registry.wallet), objectValue), readSource('payment-availability', registry.paymentAvailability?.readPaymentAvailability.bind(registry.paymentAvailability), arrayValue)]);
  const [profile, tokenBalance, billingAccount, purchases, orders, transactions, invoices, subscription, wallet, paymentAvailability] = reads;
  const input: WorkspaceCommercialSnapshotInput = { profile: profile.value, tokenBalance: tokenBalance.value, billingAccount: billingAccount.value, purchases: purchases.value, orders: orders.value ?? [], transactions: transactions.value ?? [], invoices: invoices.value ?? [], subscription: subscription.value, wallet: wallet.value, paymentAvailability: paymentAvailability.value ?? [] };
  return createSnapshotResult(assembleCommercialSnapshot(input), reads.flatMap(read => read.issue ? [read.issue] : []));
};
