import type { WorkspaceBillingContract, WorkspaceInvoiceContract, WorkspaceOrderContract, WorkspacePaymentAvailabilityContract, WorkspacePurchaseHistoryContract, WorkspaceSubscriptionContract, WorkspaceTokenBalanceContract, WorkspaceTransactionContract, WorkspaceWalletContract } from '../contracts';
import type { WorkspaceProfileContract } from './contracts';
import { createWorkspaceCommercialCapabilities } from './projection';
import type { WorkspaceCommercialCapabilities } from './projection';
export type WorkspaceCommercialDomain = 'profile' | 'token-balance' | 'billing-account' | 'purchase-history' | 'orders' | 'transactions' | 'invoices' | 'subscription' | 'wallet' | 'payment-availability';
export type WorkspaceCommercialIssueCode = 'source-unavailable' | 'source-failed' | 'invalid-data';
export interface WorkspaceCommercialIssue { readonly domain: WorkspaceCommercialDomain; readonly code: WorkspaceCommercialIssueCode; }
export type WorkspaceCommercialSnapshotState = 'ready' | 'partial' | 'unavailable';
export interface WorkspaceCommercialReadSnapshot { readonly profile: WorkspaceProfileContract | null; readonly tokenBalance: WorkspaceTokenBalanceContract | null; readonly billingAccount: WorkspaceBillingContract | null; readonly purchases: WorkspacePurchaseHistoryContract | null; readonly orders: readonly WorkspaceOrderContract[]; readonly transactions: readonly WorkspaceTransactionContract[]; readonly invoices: readonly WorkspaceInvoiceContract[]; readonly subscription: WorkspaceSubscriptionContract | null; readonly wallet: WorkspaceWalletContract | null; readonly paymentAvailability: readonly WorkspacePaymentAvailabilityContract[]; readonly capabilities: WorkspaceCommercialCapabilities; }
export interface WorkspaceCommercialSnapshotInput extends Omit<WorkspaceCommercialReadSnapshot, 'capabilities'> { readonly capabilities?: WorkspaceCommercialCapabilities; }
export type WorkspaceCommercialSnapshotResult = Readonly<{ readonly state: WorkspaceCommercialSnapshotState; readonly snapshot: WorkspaceCommercialReadSnapshot; readonly issues: readonly WorkspaceCommercialIssue[] }>;
const freezeBalance = (value: WorkspaceTokenBalanceContract): WorkspaceTokenBalanceContract => Object.freeze({ available: value.available, reserved: value.reserved, unit: value.unit });
const freezeAmount = (value: WorkspaceOrderContract['total']): WorkspaceOrderContract['total'] => Object.freeze({ amountMinor: value.amountMinor, currency: value.currency });
const freezeOrder = (value: WorkspaceOrderContract): WorkspaceOrderContract => Object.freeze({ reference: value.reference, total: freezeAmount(value.total), status: value.status });
const freezeTransaction = (value: WorkspaceTransactionContract): WorkspaceTransactionContract => Object.freeze({ reference: value.reference, amount: freezeAmount(value.amount), direction: value.direction, occurredAt: value.occurredAt });
const freezeInvoice = (value: WorkspaceInvoiceContract): WorkspaceInvoiceContract => Object.freeze({ reference: value.reference, total: freezeAmount(value.total), status: value.status, issuedAt: value.issuedAt });
const freezeOrders = (values: readonly WorkspaceOrderContract[]): readonly WorkspaceOrderContract[] => Object.freeze(values.map(freezeOrder));
const freezeTransactions = (values: readonly WorkspaceTransactionContract[]): readonly WorkspaceTransactionContract[] => Object.freeze(values.map(freezeTransaction));
const freezeInvoices = (values: readonly WorkspaceInvoiceContract[]): readonly WorkspaceInvoiceContract[] => Object.freeze(values.map(freezeInvoice));
const freezeAvailability = (values: readonly WorkspacePaymentAvailabilityContract[]): readonly WorkspacePaymentAvailabilityContract[] => Object.freeze(values.map(value => Object.freeze({ country: value.country, currency: value.currency, available: value.available })));
export const deriveCommercialCapabilities = (input: WorkspaceCommercialSnapshotInput): WorkspaceCommercialCapabilities => createWorkspaceCommercialCapabilities({ accountAvailable: input.profile !== null, billingAvailable: input.billingAccount !== null, paymentsAvailable: input.paymentAvailability.length > 0, subscriptionsAvailable: input.subscription !== null, walletAvailable: input.wallet !== null, purchaseHistoryAvailable: input.purchases !== null, ordersAvailable: input.orders.length > 0, transactionsAvailable: input.transactions.length > 0, invoicesAvailable: input.invoices.length > 0 });
export const assembleCommercialSnapshot = (input: WorkspaceCommercialSnapshotInput): WorkspaceCommercialReadSnapshot => Object.freeze({ profile: input.profile ? Object.freeze({ reference: input.profile.reference, locale: input.profile.locale, country: input.profile.country, timeZone: input.profile.timeZone }) : null, tokenBalance: input.tokenBalance ? freezeBalance(input.tokenBalance) : null, billingAccount: input.billingAccount ? Object.freeze({ accountReference: input.billingAccount.accountReference, status: input.billingAccount.status }) : null, purchases: input.purchases ? Object.freeze({ orders: freezeOrders(input.purchases.orders), transactions: freezeTransactions(input.purchases.transactions) }) : null, orders: freezeOrders(input.orders), transactions: freezeTransactions(input.transactions), invoices: freezeInvoices(input.invoices), subscription: input.subscription ? Object.freeze({ reference: input.subscription.reference, status: input.subscription.status, renewsAt: input.subscription.renewsAt }) : null, wallet: input.wallet ? Object.freeze({ reference: input.wallet.reference, tokenBalance: freezeBalance(input.wallet.tokenBalance) }) : null, paymentAvailability: freezeAvailability(input.paymentAvailability), capabilities: input.capabilities ? createWorkspaceCommercialCapabilities(input.capabilities) : deriveCommercialCapabilities(input) });
export const createEmptySnapshot = (): WorkspaceCommercialReadSnapshot => assembleCommercialSnapshot({ profile: null, tokenBalance: null, billingAccount: null, purchases: null, orders: [], transactions: [], invoices: [], subscription: null, wallet: null, paymentAvailability: [] });
export const collectSnapshotIssues = (issues: readonly WorkspaceCommercialIssue[]): readonly WorkspaceCommercialIssue[] => Object.freeze(issues.map(issue => Object.freeze({ domain: issue.domain, code: issue.code })));
const hasData = (snapshot: WorkspaceCommercialReadSnapshot): boolean => snapshot.profile !== null || snapshot.tokenBalance !== null || snapshot.billingAccount !== null || snapshot.purchases !== null || snapshot.orders.length > 0 || snapshot.transactions.length > 0 || snapshot.invoices.length > 0 || snapshot.subscription !== null || snapshot.wallet !== null || snapshot.paymentAvailability.length > 0;
export const detectSnapshotState = (snapshot: WorkspaceCommercialReadSnapshot, issues: readonly WorkspaceCommercialIssue[]): WorkspaceCommercialSnapshotState => issues.length === 0 ? 'ready' : hasData(snapshot) ? 'partial' : 'unavailable';
export const createSnapshotResult = (snapshot: WorkspaceCommercialReadSnapshot, issues: readonly WorkspaceCommercialIssue[]): WorkspaceCommercialSnapshotResult => Object.freeze({ state: detectSnapshotState(snapshot, issues), snapshot, issues: collectSnapshotIssues(issues) });
