import { describe, expect, it } from 'vitest';
import { FUTURE_WORKSPACE_EXTENSIONS, WORKSPACE_INFORMATION_ARCHITECTURE, WORKSPACE_MODALITIES, WORKSPACE_SECTION_IDS } from '../informationArchitecture';
const required = ['text','image','video','audio','tools','gallery','community','blog','learning','marketplace','projects','files','assets','history','favorites','search','notifications','settings','billing','profile'];
describe('P8A workspace information architecture', () => {
  it('contains all modalities and future placeholders', () => { expect(WORKSPACE_MODALITIES).toEqual(['text','image','video','audio','tools']); expect(WORKSPACE_SECTION_IDS).toEqual(required); });
  it('defines every section contract field', () => { for (const item of WORKSPACE_INFORMATION_ARCHITECTURE) expect(item).toEqual(expect.objectContaining({ id: expect.any(String), title: expect.any(String), icon: expect.objectContaining({kind:'placeholder'}), children: expect.any(Array), visibility: expect.stringMatching(/^(primary|future)$/), futureCapability: expect.any(Array), route: expect.objectContaining({kind:'placeholder',path:null}), description: expect.any(String) })); });
  it('is deeply immutable', () => { expect(Object.isFrozen(WORKSPACE_INFORMATION_ARCHITECTURE)).toBe(true); for (const item of WORKSPACE_INFORMATION_ARCHITECTURE) { expect(Object.isFrozen(item)).toBe(true); expect(Object.isFrozen(item.icon)).toBe(true); expect(Object.isFrozen(item.children)).toBe(true); expect(Object.isFrozen(item.futureCapability)).toBe(true); expect(Object.isFrozen(item.route)).toBe(true); for (const child of item.children) expect(Object.isFrozen(child)).toBe(true); } });
  it('includes Qwen and interoperability placeholders', () => { const text=WORKSPACE_INFORMATION_ARCHITECTURE.find(({id})=>id==='text'); expect(text?.children.map(({id})=>id)).toEqual(expect.arrayContaining(['qwen','openai-compatible','byok'])); });
  it.each(['gallery','community','blog','learning','marketplace','tools'])('contains %s', id => expect(WORKSPACE_SECTION_IDS).toContain(id));
  it('defines immutable AI, User, and Content Space extension contracts', () => { expect(FUTURE_WORKSPACE_EXTENSIONS.map(({id})=>id)).toEqual(['ai-space','user-space','content-space']); expect(Object.isFrozen(FUTURE_WORKSPACE_EXTENSIONS)).toBe(true); for(const space of FUTURE_WORKSPACE_EXTENSIONS){expect(Object.isFrozen(space)).toBe(true);expect(Object.isFrozen(space.sectionIds)).toBe(true);} });
});
