import { describe, expect, it } from 'vitest';
import { FUTURE_WORKSPACE_EXTENSIONS, WORKSPACE_INFORMATION_ARCHITECTURE, WORKSPACE_MODALITIES, WORKSPACE_SECTION_IDS } from '../informationArchitecture';
const byId = (id: string) => WORKSPACE_INFORMATION_ARCHITECTURE.find(section => section.id === id);
describe('P8B workspace information architecture', () => {
  it('preserves five modalities and adds complete platform sections', () => { expect(WORKSPACE_MODALITIES).toEqual(['text','image','video','audio','tools']); expect(WORKSPACE_SECTION_IDS).toEqual(expect.arrayContaining(['agents','workflows','knowledge-base','prompt-library','shared','trash','templates','integrations'])); });
  it('defines the final space composition contracts', () => { const spaces=Object.fromEntries(FUTURE_WORKSPACE_EXTENSIONS.map(s=>[s.id,s.sectionIds])); expect(spaces['ai-space']).toEqual(['text','image','video','audio','tools','agents','workflows']); expect(spaces['user-space']).toEqual(['projects','files','assets','knowledge-base','prompt-library','history','favorites','gallery','shared','trash','notifications','settings','billing','profile']); expect(spaces['content-space']).toEqual(['blog','learning','community','marketplace','templates','search']); });
  it('defines Agents, Workflows, Marketplace, Integrations, Knowledge and Prompts', () => { expect(byId('agents')?.children.map(x=>x.id)).toEqual(expect.arrayContaining(['openai-agents','claude-agents','deep-research','computer-use','autogpt','custom-agents'])); expect(byId('workflows')?.children.map(x=>x.id)).toEqual(expect.arrayContaining(['pipelines','automations','chains','multi-model-workflows','scheduled-flows'])); expect(byId('marketplace')?.children.map(x=>x.id)).toEqual(['models','prompts','agents','templates','plugins']); expect(byId('integrations')?.children).toHaveLength(7); expect(byId('knowledge-base')?.futureCapability).toEqual(expect.arrayContaining(['embeddings','vector-storage','retrieval','semantic-search'])); expect(byId('prompt-library')?.children).toHaveLength(6); });
  it('keeps every section and space deeply immutable', () => { expect(Object.isFrozen(WORKSPACE_INFORMATION_ARCHITECTURE)).toBe(true); for(const item of WORKSPACE_INFORMATION_ARCHITECTURE){expect(Object.isFrozen(item)).toBe(true);expect(Object.isFrozen(item.icon)).toBe(true);expect(Object.isFrozen(item.children)).toBe(true);expect(Object.isFrozen(item.futureCapability)).toBe(true);expect(Object.isFrozen(item.route)).toBe(true);for(const child of item.children)expect(Object.isFrozen(child)).toBe(true);} expect(Object.isFrozen(FUTURE_WORKSPACE_EXTENSIONS)).toBe(true);for(const space of FUTURE_WORKSPACE_EXTENSIONS){expect(Object.isFrozen(space)).toBe(true);expect(Object.isFrozen(space.sectionIds)).toBe(true);} });
});
